require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")
require("user.neovide")

spec("user.blink")
spec("user.breadcrumbs")
spec("user.catppuccin")
spec("user.colorizer")
spec("user.conform")
spec("user.eyeliner")
spec("user.gitsigns")
spec("user.lazydev")
spec("user.lsp")
spec("user.lualine")
spec("user.mini")
spec("user.modicator")
spec("user.navic")
spec("user.oil")
spec("user.snacks")
spec("user.supermaven")
spec("user.treesitter")
spec("user.typescript-tools")

-- lazy line
require("user.lazy")
